### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by rmoriz**
Hi,

I've removed a few duplicate entries in whitelists and comments. My editor also removed some trailing whitespaces, hope this is ok :-)

### CODE REVIEW

**Comment by sawanoboly** [comment]
Thanks, but two blank create lines in markdown. (in html, `<br />`).  This PR breaks layout...

Could you create new commit to revert ?

**Comment by rmoriz** [comment]
oh, that's a trap :/

I would probably suggest just using `<br />` since many editors (like mine) automatically strip trailing whitespaces without user intevention.

**Comment by rmoriz** [comment]
Here it is, had to disable my Editor config…
However, please consider switching from two trailing whitespaces to explicit `<br/>` tags.

**Comment by sawanoboly** [comment]
Thanks 😃 

> However, please consider switching from two trailing whitespaces to explicit <br/> tags.

I see. I'll replace from next time of update document.

**Pull request merged**
